language: java
sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.m2
jdk:
- oraclejdk8
install: true
script: ./travis/build.sh
notifications:
  irc: "irc.rizon.net#runelite"
  webhooks: http://discord.runelite.net/discord-webhook.php
